name: Audit

on:
  schedule:
    - cron: '0 12 * * 1'  # Weekly on Mondays at noon UTC
  workflow_dispatch:

jobs:
  audit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Audit cask
        run: |
          brew audit --cask --strict Casks/jdk26valhalla.rb || true

      - name: Test cask installation (dry run)
        run: |
          brew style Casks/jdk26valhalla.rb || true
