name: Release

on:
  push:
    branches: [main]
    paths:
      - 'Casks/jdk26valhalla.rb'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from cask
        id: version
        run: |
          VERSION=$(grep -oP 'version "\K[^"]+' Casks/jdk26valhalla.rb)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        if: steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: JDK 26 EA ${{ steps.version.outputs.version }}
          body: |
            JDK 26 Early Access Build ${{ steps.version.outputs.version }}

            ## Installation

            ```bash
            brew tap trumpyla/jdk26-ea
            brew install --cask jdk26valhalla
            ```

            For more information, visit https://jdk.java.net/26/
          draft: false
          prerelease: true
