name: Update JDK 26 EA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch latest JDK 26 EA
        id: fetch
        run: |
          # Fetch the JDK 26 page
          curl -sL https://jdk.java.net/26/ > page.html

          # Extract build number and version
          BUILD=$(grep -oP 'Build \K[0-9]+' page.html | head -1)
          VERSION="26-ea+${BUILD}"

          # Extract download URLs for macOS
          URL_MAC_ARM=$(grep -oP 'href="\K[^"]*openjdk-26-ea\+[0-9]+_macos-aarch64_bin\.tar\.gz(?=")' page.html | head -1)
          URL_MAC_INTEL=$(grep -oP 'href="\K[^"]*openjdk-26-ea\+[0-9]+_macos-x64_bin\.tar\.gz(?=")' page.html | head -1)
          URL_LINUX_X64=$(grep -oP 'href="\K[^"]*openjdk-26-ea\+[0-9]+_linux-x64_bin\.tar\.gz(?=")' page.html | head -1)

          # Download checksums
          SHA_MAC_ARM=$(curl -sL "${URL_MAC_ARM}.sha256")
          SHA_MAC_INTEL=$(curl -sL "${URL_MAC_INTEL}.sha256")
          SHA_LINUX_X64=$(curl -sL "${URL_LINUX_X64}.sha256")

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "url_mac_arm=$URL_MAC_ARM" >> $GITHUB_OUTPUT
          echo "url_mac_intel=$URL_MAC_INTEL" >> $GITHUB_OUTPUT
          echo "url_linux_x64=$URL_LINUX_X64" >> $GITHUB_OUTPUT
          echo "sha_mac_arm=$SHA_MAC_ARM" >> $GITHUB_OUTPUT
          echo "sha_mac_intel=$SHA_MAC_INTEL" >> $GITHUB_OUTPUT
          echo "sha_linux_x64=$SHA_LINUX_X64" >> $GITHUB_OUTPUT

      - name: Update cask and formula files
        run: |
          # Update cask
          sed -i "s|version \".*\"|version \"${{ steps.fetch.outputs.version }}\"|g" Casks/jdk26valhalla.rb
          sed -i "s|https://download.java.net/java/early_access/jdk26/[0-9]*/GPL/openjdk-26-ea+[0-9]*_macos-aarch64_bin.tar.gz|${{ steps.fetch.outputs.url_mac_arm }}|g" Casks/jdk26valhalla.rb
          sed -i "s|https://download.java.net/java/early_access/jdk26/[0-9]*/GPL/openjdk-26-ea+[0-9]*_macos-x64_bin.tar.gz|${{ steps.fetch.outputs.url_mac_intel }}|g" Casks/jdk26valhalla.rb
          sed -i "/macos-aarch64/,/sha256/ s|sha256 \"[^\"]*\"|sha256 \"${{ steps.fetch.outputs.sha_mac_arm }}\"|" Casks/jdk26valhalla.rb
          sed -i "/macos-x64/,/sha256/ s|sha256 \"[^\"]*\"|sha256 \"${{ steps.fetch.outputs.sha_mac_intel }}\"|" Casks/jdk26valhalla.rb

          # Update formula
          sed -i "s|version \".*\"|version \"${{ steps.fetch.outputs.version }}\"|g" Formula/jdk26valhalla.rb
          sed -i "s|https://download.java.net/java/early_access/jdk26/[0-9]*/GPL/openjdk-26-ea+[0-9]*_macos-aarch64_bin.tar.gz|${{ steps.fetch.outputs.url_mac_arm }}|g" Formula/jdk26valhalla.rb
          sed -i "s|https://download.java.net/java/early_access/jdk26/[0-9]*/GPL/openjdk-26-ea+[0-9]*_macos-x64_bin.tar.gz|${{ steps.fetch.outputs.url_mac_intel }}|g" Formula/jdk26valhalla.rb
          sed -i "s|https://download.java.net/java/early_access/jdk26/[0-9]*/GPL/openjdk-26-ea+[0-9]*_linux-x64_bin.tar.gz|${{ steps.fetch.outputs.url_linux_x64 }}|g" Formula/jdk26valhalla.rb
          sed -i "/macos-aarch64/,/sha256/ s|sha256 \"[^\"]*\"|sha256 \"${{ steps.fetch.outputs.sha_mac_arm }}\"|" Formula/jdk26valhalla.rb
          sed -i "/macos-x64/,/sha256/ s|sha256 \"[^\"]*\"|sha256 \"${{ steps.fetch.outputs.sha_mac_intel }}\"|" Formula/jdk26valhalla.rb
          sed -i "/linux-x64/,/sha256/ s|sha256 \"[^\"]*\"|sha256 \"${{ steps.fetch.outputs.sha_linux_x64 }}\"|" Formula/jdk26valhalla.rb

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update JDK 26 EA to ${{ steps.fetch.outputs.version }}"
          title: "Update JDK 26 EA to ${{ steps.fetch.outputs.version }}"
          body: |
            Auto-update JDK 26 EA to version ${{ steps.fetch.outputs.version }}

            - macOS ARM64: ${{ steps.fetch.outputs.url_mac_arm }}
            - macOS x64: ${{ steps.fetch.outputs.url_mac_intel }}
            - Linux x64: ${{ steps.fetch.outputs.url_linux_x64 }}
          branch: update-jdk26-${{ steps.fetch.outputs.version }}
          delete-branch: true
