name: Validate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm64]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        if: runner.os == 'Linux'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Validate cask syntax
        run: |
          brew style Casks/jdk26valhalla.rb || true
          ruby -c Casks/jdk26valhalla.rb
