name: Validate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate cask syntax
        run: |
          brew style --fix Casks/jdk26valhalla.rb || true
          brew audit --cask Casks/jdk26valhalla.rb || true
